# Base configs
baseurl: "https://unluckyoatmeal.github.io/photography/"
image_fulls_loc: "/images/fulls"
image_thumbs_loc: "/images/thumbs"
google_analytics: "UA-46465113-2"

# UI configs
title: "Bailey"
subtitle: "im dog"
author: "Madison Wilson"
header:
 title: "Photography"
 subtitle: "by MW"
footer:
 name: "Hey there, my name is Bailey
 bio: "I'm a dog"
